// <auto-generated />
using System;
using HighSchoolSupportSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighSchoolSupportSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006140127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("StudentPresent")
                        .HasColumnType("bit");

                    b.Property<int>("SupportSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("TutorPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceId");

                    b.HasIndex("SupportSessionId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<string>("AvailabilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("TutorId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.ExternalTutor", b =>
                {
                    b.Property<int>("ExternalTutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalTutorId"));

                    b.Property<string>("BackgroundInformation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExternalTutorId");

                    b.HasIndex("TutorId")
                        .IsUnique();

                    b.ToTable("ExternalTutors");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.ParentGuardian", b =>
                {
                    b.Property<int>("ParentGuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentGuardianId"));

                    b.Property<string>("AlternativePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RelationshipToStudent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ParentGuardianId");

                    b.ToTable("ParentGuardians");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SchoolCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SchoolId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SchoolSubject", b =>
                {
                    b.Property<int>("SchoolSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolSubjectId"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompulsory")
                        .HasColumnType("bit");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("SchoolSubjectId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectGroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SchoolSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentFeedback", b =>
                {
                    b.Property<int>("StudentFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentFeedbackId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SupportSessionId")
                        .HasColumnType("int");

                    b.HasKey("StudentFeedbackId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupportSessionId")
                        .IsUnique();

                    b.ToTable("StudentFeedbacks");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentParentGuardian", b =>
                {
                    b.Property<int>("StudentParentGuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentParentGuardianId"));

                    b.Property<int>("ParentGuardianId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentParentGuardianId");

                    b.HasIndex("ParentGuardianId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentParentGuardians");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentSubject", b =>
                {
                    b.Property<int>("StudentSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSubjectId"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("StudentSubjectId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentTutor", b =>
                {
                    b.Property<int>("StudentTutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentTutorId"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("StudentTutorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId")
                        .IsUnique();

                    b.ToTable("StudentTutors");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SubjectGroup", b =>
                {
                    b.Property<int>("SubjectGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectGroupId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("SubjectGroupId");

                    b.HasIndex("GradeId");

                    b.ToTable("SubjectGroups");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportRequest", b =>
                {
                    b.Property<int>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportRequestId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SupportRequests");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportSession", b =>
                {
                    b.Property<int>("SupportSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportSessionId"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TutorAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("SupportSessionId");

                    b.HasIndex("TutorAssignmentId");

                    b.ToTable("SupportSessions");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TeacherStudent", b =>
                {
                    b.Property<int>("TeacherStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherStudentId"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TeacherStudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherStudents");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TutorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TutorId");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorApproval", b =>
                {
                    b.Property<int>("TutorApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorApprovalId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ApprovedByTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorApprovalId");

                    b.HasIndex("ApprovedByTeacherId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorApprovals");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorAssignment", b =>
                {
                    b.Property<int>("TutorAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorAssignmentId"));

                    b.Property<int>("AssignedByTeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupportRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorAssignmentId");

                    b.HasIndex("AssignedByTeacherId");

                    b.HasIndex("SupportRequestId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorAssignments");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorFeedback", b =>
                {
                    b.Property<int>("TutorFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorFeedbackId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SupportSessionId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorFeedbackId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupportSessionId")
                        .IsUnique();

                    b.HasIndex("TutorId");

                    b.ToTable("TutorFeedbacks");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorSubject", b =>
                {
                    b.Property<int>("TutorSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorSubjectId"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("TutorSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Attendance", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.SupportSession", "SupportSession")
                        .WithOne("Attendance")
                        .HasForeignKey("HighSchoolSupportSystem.Models.Attendance", "SupportSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupportSession");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Availability", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithMany("Availabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.ExternalTutor", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithOne("ExternalTutor")
                        .HasForeignKey("HighSchoolSupportSystem.Models.ExternalTutor", "TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Grade", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.School", "School")
                        .WithMany("Grades")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Notification", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SchoolSubject", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Grade", "Grade")
                        .WithMany("SchoolSubjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.School", "School")
                        .WithMany("SchoolSubjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.SubjectGroup", "SubjectGroup")
                        .WithMany("SchoolSubjects")
                        .HasForeignKey("SubjectGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HighSchoolSupportSystem.Models.Subject", "Subject")
                        .WithMany("SchoolSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("SubjectGroup");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Student", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentFeedback", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("StudentFeedbacks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.SupportSession", "SupportSession")
                        .WithOne("StudentFeedback")
                        .HasForeignKey("HighSchoolSupportSystem.Models.StudentFeedback", "SupportSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("SupportSession");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentParentGuardian", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.ParentGuardian", "ParentGuardian")
                        .WithMany("StudentParentGuardians")
                        .HasForeignKey("ParentGuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("StudentParentGuardians")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentGuardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentSubject", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.StudentTutor", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("StudentTutors")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithOne("StudentTutor")
                        .HasForeignKey("HighSchoolSupportSystem.Models.StudentTutor", "TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SubjectGroup", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Grade", "Grade")
                        .WithMany("SubjectGroups")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportRequest", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.User", "CreatedByUser")
                        .WithMany("SupportRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("SupportRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportSession", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.TutorAssignment", "TutorAssignment")
                        .WithMany("SupportSessions")
                        .HasForeignKey("TutorAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TutorAssignment");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TeacherStudent", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Teacher", "Teacher")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorApproval", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Teacher", "ApprovedByTeacher")
                        .WithMany("TutorApprovals")
                        .HasForeignKey("ApprovedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithMany("TutorApprovals")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByTeacher");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorAssignment", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Teacher", "AssignedByTeacher")
                        .WithMany("TutorAssignments")
                        .HasForeignKey("AssignedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.SupportRequest", "SupportRequest")
                        .WithMany("TutorAssignments")
                        .HasForeignKey("SupportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithMany("TutorAssignments")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByTeacher");

                    b.Navigation("SupportRequest");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorFeedback", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.SupportSession", "SupportSession")
                        .WithOne("TutorFeedback")
                        .HasForeignKey("HighSchoolSupportSystem.Models.TutorFeedback", "SupportSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithMany("TutorFeedbacks")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("SupportSession");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorSubject", b =>
                {
                    b.HasOne("HighSchoolSupportSystem.Models.Subject", "Subject")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HighSchoolSupportSystem.Models.Tutor", "Tutor")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Grade", b =>
                {
                    b.Navigation("SchoolSubjects");

                    b.Navigation("Students");

                    b.Navigation("SubjectGroups");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.ParentGuardian", b =>
                {
                    b.Navigation("StudentParentGuardians");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.School", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("SchoolSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Student", b =>
                {
                    b.Navigation("StudentFeedbacks");

                    b.Navigation("StudentParentGuardians");

                    b.Navigation("StudentSubjects");

                    b.Navigation("StudentTutors");

                    b.Navigation("SupportRequests");

                    b.Navigation("TeacherStudents");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Subject", b =>
                {
                    b.Navigation("SchoolSubjects");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SubjectGroup", b =>
                {
                    b.Navigation("SchoolSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportRequest", b =>
                {
                    b.Navigation("TutorAssignments");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.SupportSession", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("StudentFeedback");

                    b.Navigation("TutorFeedback");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Teacher", b =>
                {
                    b.Navigation("TeacherStudents");

                    b.Navigation("TutorApprovals");

                    b.Navigation("TutorAssignments");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.Tutor", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ExternalTutor");

                    b.Navigation("StudentTutor");

                    b.Navigation("TutorApprovals");

                    b.Navigation("TutorAssignments");

                    b.Navigation("TutorFeedbacks");

                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.TutorAssignment", b =>
                {
                    b.Navigation("SupportSessions");
                });

            modelBuilder.Entity("HighSchoolSupportSystem.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SupportRequestsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
